### ISSUE TITLE
ImportError: No module named 'wsgidav.server'

### ISSUE THREAD

**Issue by MrMoronIV** [mar10/wsgidav#106]
`pip install git+https://github.com/mar10/wsgidav.git`

```
Installing collected packages: jsmin, MarkupSafe, Jinja2, PyYAML, WsgiDAV
  Running setup.py install for jsmin ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for WsgiDAV ... done
Successfully installed Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.12 WsgiDAV-3.0.0a2 jsmin-2.2.2
```

`wsgidav --version` gives:
```
Traceback (most recent call last):
  File "/usr/bin/wsgidav", line 9, in <module>
    load_entry_point('WsgiDAV==3.0.0a2', 'console_scripts', 'wsgidav')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'wsgidav.server'
```

I did not install cheroot, cause I want to use nginx as my webserver.

Edit: Well after I installed cheroot it gives the same error, wsgidav version 3.0.0a2 seems pretty broken to me. Call me a whimp, but at least 2.2.4 seems to give me back the version number I ask for

**Comment by mar10** [comment]
Thanks for reporting, should work now.

```
wsgidav --version -v
```
You don't need to install cheroot, but a WSGI compliant server is required ([see here][1])
WsgiDAV comes with a builtin `wsgiref`, 
```
wsgidav --root . --server wsgiref
```
but being single threaded is not fit for production scenarios.
cheroot, gunicorn, etc. may be  better choices.

[1]: https://www.fullstackpython.com/nginx.html

**Comment by MrMoronIV** [comment]
This is confirmed working now, thank you for taking care of it!
