### ISSUE TITLE
digest auth broken on release WsgiDav==3.0.0a4

### ISSUE THREAD

**Issue by jaredrunyon** [mar10/wsgidav#135]
Not sure if I am the only one experiencing this issue but it appears that digest auth is broken in newest release `WsgiDav==3.0.0a4`. I have made the fix in a feature branch based off of master but am unable to push the feature branch and open a PR (403 from github). 

I would love to contribute to the project and open a PR if you give me access (assuming this is a real issue).

```
2018-11-23 21:24:55.758 - <140603089622784> wsgidav.error_printer       ERROR   :  Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/vagrant/venv/lib/python3.5/site-packages/wsgidav/error_printer.py", line 46, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/vagrant/venv/lib/python3.5/site-packages/wsgidav/http_authenticator.py", line 211, in __call__
    return self.auth_digest_auth_request(environ, start_response)
  File "/vagrant/venv/lib/python3.5/site-packages/wsgidav/http_authenticator.py", line 492, in auth_digest_auth_request
    req_username, realm_name
UnboundLocalError: local variable 'req_username' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/venv/lib/python3.5/site-packages/wsgidav/error_printer.py", line 83, in __call__
    raise as_DAVError(e)
wsgidav.dav_error.DAVError: DAVError(500 Internal Server Error: An internal server error occurred
    Source exception: 'local variable 'req_username' referenced before assignment')

2018-11-23 21:24:55.758 - <140603089622784> wsgidav.error_printer       ERROR   :  e.src_exception:
local variable 'req_username' referenced before assignment
2018-11-23 21:24:55.758 - <140603089622784> wsgidav.wsgidav_app         INFO    :  192.168.56.1 - (anonymous) - [2018-11-23 21:24:55] "OPTIONS " elap=0.005sec -> 500 Internal Server Error
```

**Comment by jaredrunyon** [comment]
Just realized you guys probably follow the Fork PR Workflow? I can do that.

**Comment by mar10** [comment]
Thanks, forking first should work.
