### ISSUE TITLE
Config File Example seems to be deprecated

### ISSUE THREAD

**Issue by akloster** [mar10/wsgidav#147]
I'm trying to run the example, but I am getting this traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/wsgidav", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/wsgidav/server/server_cli.py", line 767, in run
    app = WsgiDAVApp(config)
  File "/usr/local/lib/python3.6/site-packages/wsgidav/wsgidav_app.py", line 134, in __init__
    _check_config(config)
  File "/usr/local/lib/python3.6/site-packages/wsgidav/wsgidav_app.py", line 118, in _check_config
    raise ValueError("Invalid configuration:\n  - " + "\n  - ".join(errors))
ValueError: Invalid configuration:
  - Deprecated option 'user_mapping': use 'simple_dc.user_mapping' instead.
```

Am I doing something wrong?

**Comment by mar10** [comment]
Which version are you using? Can you pots the config file?
(With version v3.0, the yams format is preferred.)
