### ISSUE TITLE
Implementing Custom Provider - No stack trace - 500 Internal Server Error: An internal server error occurred Source exception: ''

### ISSUE THREAD

**Issue by AdrianVollmer** [mar10/wsgidav#150]
Hi, first of all thanks for this project.

I'm trying to implement my own provider. In a browser, I see this error message:
```
500 Internal Server Error: An internal server error occurred Source exception: ''
```
On the command line, there is nothing. So I can't figure out what's wrong.

The code is fairly simple (see below). Am I doing something wrong? A full stack trace would be very helpful. I'm using Python 3.7.3rc1 and wsgidav 3.0.0.

```
#!/usr/bin/env python3
import io
from cheroot import wsgi
from wsgidav.wsgidav_app import WsgiDAVApp
from wsgidav.dav_provider import DAVProvider, DAVNonCollection


def webdav_content(path):
    return "test"+path


class DynamicCollection(DAVNonCollection):
    def get_content_length(self):
        return len(webdav_content(self.path))

    def get_content_type(self):
        return 'text/plain'

    def get_content(self):
        content = webdav_content(self.path)
        string_out = io.StringIO(content)
        print(content)
        return string_out


class MyProvider(DAVProvider):
    def get_resource_inst(self, path, environ):
        return DynamicCollection(path, environ)


config = {
    "host": '0.0.0.0',
    "port": 8001,
    "dir_browser": {"enable": True},
    "http_authenticator": {
        # None: dc.simple_dc.SimpleDomainController(user_mapping)
        "domain_controller": None,
        "accept_basic": True,  # Allow basic authentication, True or False
        "accept_digest": True,  # Allow digest authentication, True or False
        "default_to_digest": True,  # True  or False
        # Name of a header field that will be accepted as authorized user
        "trusted_auth_header": None,
    },
    #: Used by SimpleDomainController only
    "simple_dc": {"user_mapping": {"*": True}},
    "provider_mapping": {
        "/": MyProvider(),
    },
    "verbose": 1,
    }

app = WsgiDAVApp(config)
server_args = {
    "bind_addr": (config["host"], config["port"]),
    "wsgi_app": app,
    }
server = wsgi.Server(**server_args)
server.start()
```

**Comment by mar10** [comment]
Hi,

logging is disabled by default, because not all apps want their libraries verbose.
[You can enable logging](https://wsgidav.readthedocs.io/en/latest/user_guide_lib.html?highlight=logging#logging) like so

```py
import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("wsgidav")
logger.propagate = True
logger.setLevel(logging.DEBUG)
```

If you prefer, you can also increase verbosity
```py
config = {
    "host": '0.0.0.0',
    "port": 8001,
    ...
    "verbose": 5,
    }

app = WsgiDAVApp(config)
```

Now you can see the root cause:
```tb
INFO:wsgidav.debug_filter:

test/
ERROR:wsgidav.error_printer:Traceback (most recent call last):
  File "/Users/martin/prj/git/wsgidav/wsgidav/error_printer.py", line 52, in __call__
    for v in app_iter:
  File "/Users/martin/prj/git/wsgidav/wsgidav/request_resolver.py", line 213, in __call__
    for v in app_iter:
  File "/Users/martin/prj/git/wsgidav/wsgidav/request_server.py", line 130, in __call__
    for v in app_iter:
  File "/Users/martin/prj/git/wsgidav/wsgidav/request_server.py", line 1629, in _send_resource
    assert compat.is_bytes(readbuffer)
AssertionError
```

WSGI demands content to be binary strings.
You can fix it like so:
```py
def webdav_content(path):
    # Should be bytes
    return ("test" + path).encode()


class DynamicCollection(DAVNonCollection):
    def get_content_length(self):
        return len(webdav_content(self.path))

    def get_content_type(self):
        return 'text/plain'

    def get_content(self):
        content = webdav_content(self.path)
        # string_out = io.StringIO(content)
        string_out = io.BytesIO(content)  # Bytes expected
        print(content)
        return string_out
```

**Comment by AdrianVollmer** [comment]
Gotcha. Thanks a lot!
