### ISSUE TITLE
False exception when user accessing unhandled realm

### ISSUE THREAD

**Issue by kalemas** [mar10/wsgidav#217]
Following exception occur whenever user attempts to access realm that is not handled by configuration:

```
Caught Exception
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/wsgidav/error_printer.py", line 50, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/opt/app-root/lib/python3.6/site-packages/wsgidav/http_authenticator.py", line 271, in __call__
    return self.send_basic_auth_response(environ, start_response)
  File "/opt/app-root/lib/python3.6/site-packages/wsgidav/http_authenticator.py", line 276, in send_basic_auth_response
    wwwauthheaders = 'Basic realm="' + realm + '"'
TypeError: must be str, not NoneType
```

But this is not something that cant be expected by developer.

What do you think? Our error tracking system encounter this false cases eventually because of this. I would make PR to handle this case without raising an exception.

**Comment by mar10** [comment]
Sorry, I missed this issue. Yes, a PR would be great
