### ISSUE TITLE
Not mapped root folder produces internal error

### ISSUE THREAD

**Issue by de666** [mar10/wsgidav#233]
With this configuration file settings:
```
mount_path: null

provider_mapping:
    "/music":
        root: "/music"
        readonly: true
    "/music_mp3":
        root: "/mnt"
        readonly: true
		
# Additional options for SimpleDomainController only:
simple_dc:
    # Access control per share.
    # These routes must match the provider mapping.
    # NOTE: Provider routes without a matching entry here, are inaccessible.
    user_mapping:
        "*":  # default (used for all shares that are not explicitly listed)
            "xxxxxx":
                password: "xxxxxx"
```

A "PROPFIND /" request produces:
```
14:48:37.778 - <1760490592> wsgidav.dc.base_dc          WARNING : _calc_realm_from_path_provider('/'): 'None'
14:48:37.779 - <1760490592> wsgidav.dc.base_dc          WARNING : _calc_realm_from_path_provider('/'): 'None'
14:48:37.780 - <1760490592> wsgidav.error_printer       ERROR   : Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wsgidav/error_printer.py", line 50, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/usr/local/lib/python3.8/dist-packages/wsgidav/http_authenticator.py", line 245, in __call__
    return self.handle_digest_auth_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/wsgidav/http_authenticator.py", line 426, in handle_digest_auth_request
    if auth_header_dict["realm"].upper() != realm.upper():
AttributeError: 'NoneType' object has no attribute 'upper'

14:48:37.780 - <1760490592> wsgidav.error_printer       ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wsgidav/error_printer.py", line 50, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/usr/local/lib/python3.8/dist-packages/wsgidav/http_authenticator.py", line 245, in __call__
    return self.handle_digest_auth_request(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/wsgidav/http_authenticator.py", line 426, in handle_digest_auth_request
    if auth_header_dict["realm"].upper() != realm.upper():
AttributeError: 'NoneType' object has no attribute 'upper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wsgidav/error_printer.py", line 87, in __call__
    raise as_DAVError(e)
wsgidav.dav_error.DAVError: DAVError(500 Internal Server Error: An internal server error occurred
    Source exception: ''NoneType' object has no attribute 'upper'')

14:48:37.781 - <1760490592> wsgidav.error_printer       ERROR   : e.src_exception:
'NoneType' object has no attribute 'upper'
14:48:37.781 - <1760490592> wsgidav.wsgidav_app         INFO    : 185.187.62.234 - (anonymous) - [2021-11-05 14:48:37] "PROPFIND /" length=84, depth=0, elap=0.003sec -> 500 Internal Server Error

```
I think the response code should be something link 4xx (maybe not found or not authorized)

**Comment by mar10** [comment]
I wasn't able to reproduce it. Can you please give more information?

![image](https://user-images.githubusercontent.com/41663/140650777-3dd03225-56a9-423a-b96d-da35fd45611a.png)

**Comment by de666** [comment]
starting from the default yaml configuration file, I make the following modifications in addition to the other settings I wrote in the first comment:

- Enable ssl
- Disable directory browsing putting
```
dir_browser:
    enable: false
```
anyway full configuration file here below
[wsgidav.zip](https://github.com/mar10/wsgidav/files/7495700/wsgidav.zip)

This is what I see connecting from a web browser
![Immagine 2021-11-08 102228](https://user-images.githubusercontent.com/4525838/140716250-565f825a-1f21-481a-8954-5e535821efa9.png)
