### ISSUE TITLE
Cant write data into folders [Windows 10]

### ISSUE THREAD

**Issue by Milor123** [mar10/wsgidav#252]
**Bug??**
Simply try to connect my phone with Davx5, i can create folder a navegate but cant copy a file with data. (I try use .yaml config, I try 1000 things, but i have the same problem.)

**Expected behavior**

My users have R/W permissions  and the cmd are with admin privilegies

**Screenshots, Log-Files, Stacktrace**
![imagen](https://user-images.githubusercontent.com/14153649/164571340-d5770ac8-a6dd-414f-bd29-d3fc33ed3211.png)

![imagen](https://user-images.githubusercontent.com/14153649/164571349-3c4aaff8-3a20-47ee-953f-338cc93b3753.png)

```
E:\>wsgidav.exe --port=8080 --host=192.168.20.245 --root=/Webdav_Server/MyFilesSecure --auth=anonymous
Running without configuration file.
19:15:11.838 - WARNING : App wsgidav.mw.cors.Cors(None).is_disabled() returned True: skipping.
19:15:11.860 - INFO    : WsgiDAV/4.0.1 Python/3.9.9 Windows-10-10.0.19044
19:15:11.861 - INFO    : Lock manager:      LockManager(LockStorageDict)
19:15:11.861 - INFO    : Property manager:  None
19:15:11.861 - INFO    : Domain controller: SimpleDomainController()
19:15:11.861 - INFO    : Registered DAV providers by route:
19:15:11.862 - INFO    :   - '/:dir_browser': FilesystemProvider for path 'E:\Webdav_Server\lib\wsgidav\dir_browser\htdocs' (Read-Only) (anonymous)
19:15:11.862 - INFO    :   - '/': FilesystemProvider for path 'E:\Webdav_Server\MyFilesSecure' (Read-Write) (anonymous)
19:15:11.862 - WARNING : Basic authentication is enabled: It is highly recommended to enable SSL.
19:15:11.862 - WARNING : Share '/' will allow anonymous write access.
19:15:11.862 - WARNING : Share '/:dir_browser' will allow anonymous read access.
19:15:11.975 - INFO    : Running WsgiDAV/4.0.1 Cheroot/8.6.0 Python 3.9.9
19:15:11.976 - INFO    : Serving on http://192.168.20.245:8080 ...
19:15:13.726 - INFO    : Got OPTIONS '/' request
19:15:13.831 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:13] "PROPFIND /" length=335, depth=1, elap=0.105sec -> 207 Multi-Status
19:15:14.927 - INFO    : Got OPTIONS '/' request
19:15:14.928 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:14] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
19:15:24.977 - INFO    : Got OPTIONS '/' request
19:15:24.978 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:24] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
19:15:26.141 - INFO    : Got OPTIONS '/' request
19:15:26.143 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.002sec -> 207 Multi-Status
19:15:26.143 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "COPY /secure.txt" dest="http://192.168.20.245:8080/secure.txt", length=0, depth=0, overwrite=T, elap=0.001sec -> 403 Forbidden
19:15:26.174 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PUT /secure.txt" length=0, elap=0.001sec -> 412 Precondition Failed
19:15:26.195 - INFO    : Got OPTIONS '/' request
19:15:26.196 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PUT /secure_1.txt" length=0, elap=0.001sec -> 412 Precondition Failed
19:15:26.197 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.002sec -> 207 Multi-Status
19:15:26.259 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PUT /secure_2.txt" length=0, elap=0.001sec -> 201 Created
19:15:26.260 - INFO    : Got OPTIONS '/' request
19:15:26.261 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.002sec -> 207 Multi-Status
19:15:26.328 - INFO    : Got OPTIONS '/' request
19:15:26.329 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
19:15:26.371 - INFO    : Got OPTIONS '/' request
19:15:26.372 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
19:15:26.416 - INFO    : Got OPTIONS '/' request
19:15:26.417 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
19:15:26.458 - INFO    : Got OPTIONS '/' request
19:15:26.459 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
19:15:26.503 - INFO    : Got OPTIONS '/' request
19:15:26.504 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.002sec -> 207 Multi-Status
19:15:26.550 - INFO    : Got OPTIONS '/' request
19:15:26.551 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:26] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
19:15:30.962 - INFO    : Got OPTIONS '/' request
19:15:30.964 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:30] "PROPFIND /" length=335, depth=1, elap=0.002sec -> 207 Multi-Status
19:15:31.659 - INFO    : Got OPTIONS '/' request
19:15:31.660 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:31] "PROPFIND /" length=335, depth=1, elap=0.002sec -> 207 Multi-Status
19:15:32.495 - INFO    : Got OPTIONS '/' request
19:15:32.496 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-22 00:15:32] "PROPFIND /" length=335, depth=1, elap=0.001sec -> 207 Multi-Status
```

my files are
![imagen](https://user-images.githubusercontent.com/14153649/164571932-06aac349-5bb6-4150-8636-d03716b0a4fc.png)

Android connection, try copy secure.txt to the same folder, I get 0 bytes files
![imagen](https://user-images.githubusercontent.com/14153649/164571122-344c3877-5794-4cb2-b981-81e36f2d693d.png)

If applicable, add a log file (consider `--verbose`).

**Environment:**
```
E:\>wsgidav.exe --version
4.0.1
```

WSGI server cheroot? Its default
Which WebDAV client was used (Davx5 on rooted android)

Please help me, what should i do?

**Comment by mar10** [comment]
Please run with --verbose option and send the log file.
Also try with another WebDAV client (File Explorer, macOS finder, Konqueror or similar)

**Comment by Milor123** [comment]
> Please run with --verbose option and send the log file. Also try with another WebDAV client (File Explorer, macOS finder, Konqueror or similar)

Ohh you have reason!! Using other WebDav Client it work for me...

and using davx5 for webdav, show this and keep stucked in 0 bytes files, do you know why? 
```
Running without configuration file.
14:05:50.854 - WARNING : App wsgidav.mw.cors.Cors(None).is_disabled() returned True: skipping.
14:05:50.875 - INFO    : WsgiDAV/4.0.1 Python/3.9.9 Windows-10-10.0.19044
14:05:50.875 - INFO    : Default encoding: 'utf-8' (file system: 'utf-8')
14:05:50.875 - INFO    : Lock manager:      LockManager(LockStorageDict)
14:05:50.875 - INFO    : Property manager:  None
14:05:50.875 - INFO    : Domain controller: SimpleDomainController()
14:05:50.875 - INFO    : Middleware stack:
14:05:50.875 - INFO    :   - wsgidav.error_printer.ErrorPrinter
14:05:50.875 - INFO    :   - wsgidav.http_authenticator.HTTPAuthenticator
14:05:50.875 - INFO    :   - wsgidav.dir_browser._dir_browser.WsgiDavDirBrowser
14:05:50.875 - INFO    :   - wsgidav.request_resolver.RequestResolver
14:05:50.876 - INFO    : Registered DAV providers by route:
14:05:50.876 - INFO    :   - '/:dir_browser': FilesystemProvider for path 'E:\Webdav_Server\lib\wsgidav\dir_browser\htdocs' (Read-Only) (anonymous)
14:05:50.876 - INFO    :   - '/': FilesystemProvider for path 'E:\Webdav_Server\MyFilesSecure' (Read-Write) (anonymous)
14:05:50.876 - WARNING : Basic authentication is enabled: It is highly recommended to enable SSL.
14:05:50.876 - WARNING : Share '/' will allow anonymous write access.
14:05:50.876 - WARNING : Share '/:dir_browser' will allow anonymous read access.
14:05:50.993 - INFO    : Running WsgiDAV/4.0.1 Cheroot/8.6.0 Python 3.9.9
14:05:50.993 - INFO    : Serving on http://192.168.20.245:8080 ...
14:05:53.906 - INFO    : Got OPTIONS '/' request
14:05:53.906 - INFO    : Got OPTIONS '/' request
14:05:53.906 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:05:53] "OPTIONS /" length=0, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.000sec -> 200 OK
14:05:54.214 - INFO    : Got OPTIONS '/' request
14:05:54.352 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:05:54] "PROPFIND /" length=335, depth=1, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.138sec -> 207 Multi-Status
14:05:57.607 - INFO    : Got OPTIONS '/' request
14:05:57.609 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:05:57] "PROPFIND /" length=335, depth=1, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.002sec -> 207 Multi-Status
14:06:04.934 - INFO    : Got OPTIONS '/' request
14:06:04.936 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:06:04] "PROPFIND /" length=335, depth=1, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.002sec -> 207 Multi-Status
14:06:27.548 - INFO    : Got OPTIONS '/' request
14:06:27.550 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:06:27] "PROPFIND /" length=335, depth=1, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.002sec -> 207 Multi-Status
14:06:29.348 - DEBUG   : Caught (412, 'If-None-Match header condition failed')
14:06:29.348 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:06:29] "PUT /MotoDolby-GPro-MagiskModule-20220416153455.zip" length=0, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.001sec -> 412 Precondition Failed
14:06:29.410 - DEBUG   : check_write_permission(/, 0, [], )
14:06:29.410 - DEBUG   :   checking /
14:06:29.412 - DEBUG   : PUT: Content-Length == 0. Creating empty file...
14:06:29.412 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:06:29] "PUT /MotoDolby-GPro-MagiskModule-20220416153455_1.zip" length=0, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.002sec -> 201 Created
14:06:29.491 - INFO    : Got OPTIONS '/' request
14:06:29.493 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:06:29] "PROPFIND /" length=335, depth=1, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.002sec -> 207 Multi-Status
14:06:29.536 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:06:29] "HEAD /MotoDolby-GPro-MagiskModule-20220416153455_1.zip" depth=0, connection="Keep-Alive", agent="DAVx5/4.1.1-mgd (2022/02/01; dav4jvm; okhttp/4.9.1) Android/12", elap=0.001sec -> 200 OK
14:06:29.595 - DEBUG   : check_write_permission(/MotoDolby-GPro-MagiskModule-20220416153455_1.zip, 0, [], )
14:06:29.596 - DEBUG   :   checking /MotoDolby-GPro-MagiskModule-20220416153455_1.zip
14:06:29.596 - DEBUG   :   checking /
14:06:59.970 - DEBUG   : check_write_permission(/, 0, [], )
14:06:59.986 - DEBUG   :   checking /
14:07:00.033 - DEBUG   : check_write_permission(/MotoDolby-GPro-MagiskModule-20220416153455_1.zip, 0, [], )
14:07:00.049 - DEBUG   :   checking /MotoDolby-GPro-MagiskModule-20220416153455_1.zip
14:07:00.065 - DEBUG   :   checking /
14:07:00.210 - ERROR   : Traceback (most recent call last):
  File "C:\prj\git\wsgidav\wsgidav\error_printer.py", line 50, in __call__
  File "C:\prj\git\wsgidav\wsgidav\request_resolver.py", line 224, in __call__
  File "C:\prj\git\wsgidav\wsgidav\request_server.py", line 127, in __call__
  File "C:\prj\git\wsgidav\wsgidav\dav_provider.py", line 1584, in custom_request_handler
  File "C:\prj\git\wsgidav\wsgidav\request_server.py", line 649, in do_DELETE
  File "C:\prj\git\wsgidav\wsgidav\fs_dav_provider.py", line 106, in delete
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'E:\\Webdav_Server\\MyFilesSecure\\MotoDolby-GPro-MagiskModule-20220416153455_1.zip'

14:07:00.222 - DEBUG   : Caught 500
14:07:00.346 - ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "C:\prj\git\wsgidav\wsgidav\error_printer.py", line 50, in __call__
  File "C:\prj\git\wsgidav\wsgidav\request_resolver.py", line 224, in __call__
  File "C:\prj\git\wsgidav\wsgidav\request_server.py", line 127, in __call__
  File "C:\prj\git\wsgidav\wsgidav\dav_provider.py", line 1584, in custom_request_handler
  File "C:\prj\git\wsgidav\wsgidav\request_server.py", line 649, in do_DELETE
  File "C:\prj\git\wsgidav\wsgidav\fs_dav_provider.py", line 106, in delete
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'E:\\Webdav_Server\\MyFilesSecure\\MotoDolby-GPro-MagiskModule-20220416153455_1.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\prj\git\wsgidav\wsgidav\error_printer.py", line 83, in __call__
wsgidav.dav_error.DAVError: 500

14:07:00.361 - ERROR   : e.src_exception:
[WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'E:\\Webdav_Server\\MyFilesSecure\\MotoDolby-GPro-MagiskModule-20220416153455_1.zip'
14:07:00.377 - INFO    : 192.168.20.51 - (anonymous) - [2022-04-24 19:07:00] "DELETE /MotoDolby-GPro-MagiskModule-20220416153455_1.zip"
```

What could I do? I need use davx5 for do a backup using a native tool of my android 12. T_T Thank u very much for u reply!
