### ISSUE TITLE
TypeError: get_dict_value() got an unexpected keyword argument 'as_dict'

### ISSUE THREAD

**Issue by RemiZOffAlex** [mar10/wsgidav#264]
```
python3.10 ./wsgidav/server/server_cli.py  -c ./sample_wsgidav.yaml 
Traceback (most recent call last):
  File "/wsgidav/server/server_cli.py", line 843, in <module>
    run()
  File "/wsgidav/server/server_cli.py", line 799, in run
    cli_opts, config = _init_config()
  File "/wsgidav/server/server_cli.py", line 368, in _init_config
    auth_conf = util.get_dict_value(config, "http_authenticator", as_dict=True)
TypeError: get_dict_value() got an unexpected keyword argument 'as_dict'
```

**Comment by RemiZOffAlex** [comment]
Sorry! This error from old package exist in system.
