### ISSUE TITLE
No module name wsgidav.mw

### ISSUE THREAD

**Issue by tarun-rogers** [mar10/wsgidav#269]
**Unable to run wsgidav with separate config.yaml**
I am trying to setup webdav in kuberntes pod and for that i am using wsgidav image.
once logging in the pod. I am running below command with some different configurations.

wsgidav -c config5.yaml.

I am getting below error.
/uploads # wsgidav -c config5.yaml
2022-10-19 17:44:26.270 - <139634859264840> wsgidav                     ERROR   :  Dynamic import of 'wsgidav.mw.cors.Cors' failed: No module named 'wsgidav.mw'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wsgidav/util.py", line 278, in dynamic_import_class
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgidav.mw'
Traceback (most recent call last):
  File "/usr/local/bin/wsgidav", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/wsgidav/server/server_cli.py", line 853, in run
    app = WsgiDAVApp(config)
/uploads # wsgidav -c config5.yaml
2022-10-19 17:52:39.674 - <140399917681480> wsgidav                     ERROR   :  Dynamic import of 'wsgidav.mw.cors.Cors' failed: No module named 'wsgidav.mw'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wsgidav/util.py", line 278, in dynamic_import_class
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgidav.mw'
Traceback (most recent call last):
  File "/usr/local/bin/wsgidav", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/wsgidav/server/server_cli.py", line 853, in run
    app = WsgiDAVApp(config)
  File "/usr/local/lib/python3.9/site-packages/wsgidav/wsgidav_app.py", line 201, in __init__
    app_class = dynamic_import_class(mw)
  File "/usr/local/lib/python3.9/site-packages/wsgidav/util.py", line 278, in dynamic_import_class
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgidav.mw'

**Environment:**
```
WsgiDAV/3.1.1 Python/3.9.6(64 bit) Linux-4.15.0-194-generic-x86_64-with
Python from: /usr/local/bin/python
```

Which WSGI server was used (cheroot, ext-wsgiutils, gevent, gunicorn, paste, uvicorn, wsgiref, ...)?
cheroot

Which WebDAV client was used (MS File Explorer, MS Office, macOS Finder, WinSCP, Windows, file mapping, ...)?

**Additional context**

**Comment by mar10** [comment]
Does it work with the latest version?
