### ISSUE TITLE
(minor) Don't default to cheroot if it is not installed by default

### ISSUE THREAD

**Issue by chrisv2** [mar10/wsgidav#74]
# Steps to reproduce

```bash
mkvirtualenv wsgidav-py3 -ppython3 
pip install -e git+ssh://git@github.com:mar10/wsgidav.git#egg=wsgidav
wsgidav --host=0.0.0.0 --port=8088 --root=/some/folder -v
```

# Expected Result
Server should serve the content of /some/folder

# Actual Result
```
Running without configuration file.
<140526985504512> [10:00:26.17] wsgidav:  Default encoding: ascii (file system: UTF-8)
Middleware <class 'wsgidav.dir_browser.WsgiDavDirBrowser'> is suitable
Middleware <class 'wsgidav.http_authenticator.HTTPAuthenticator'> is suitable
Middleware <class 'wsgidav.error_printer.ErrorPrinter'> is suitable
Middleware <class 'wsgidav.debug_filter.WsgiDavDebugFilter'> is suitable
Using lock manager: LockManager(LockStorageDict)
Using property manager: None
Using domain controller: WsgiDAVDomainController
Registered DAV providers:
  Share '/': FilesystemProvider for path '/some/folder' (Read-Write) (anonymous)
WARNING: share '/' will allow anonymous access.
******************************************************************************
ERROR: Could not import Cheroot.
Try `pip install cheroot` or specify another server using the --server option.
******************************************************************************
Traceback (most recent call last):
  File "[...]/.local/bin/wsgidav", line 9, in <module>
    load_entry_point('WsgiDAV', 'console_scripts', 'wsgidav')()
  File "/tmp/src/wsgidav/wsgidav/server/run_server.py", line 591, in run
    handler(app, config, server)
  File "/tmp/src/wsgidav/wsgidav/server/run_server.py", line 435, in _runCheroot
    from cheroot import server, wsgi
ImportError: No module named cheroot
```

While the error message is helpful and adding `--server=ext-wsgiutils` to the command line fixes the problem, I still think wsgidav should either fall back to the internal server when there are no other options available. Alternatively, the README could be fixed to include the necessary --server setting.

**Comment by mar10** [comment]
Thanks. I updated the docs (wsgiutils is not a serious server, so using cheroot is recommended)
