### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)

### ISSUE THREAD

**Issue by sarnobat** [mar10/wsgidav#94]
How difficult would it be to support unicode characters? I have a lot of images and videos in Spanish language. If it fails, the entire request fails. It would be great if the file could simply be skipped at least.

```
UnicodeDecodeError('ascii', 'intercontinental 1974 atl\xc3\xa9tico   independiente.mp4', 25, 26, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1152, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 974, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/wsgi.py", line 133, in respond
    for chunk in filter(None, response):
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/wsgidav_app.py", line 435, in __call__
    for v in app_iter:
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/debug_filter.py", line 161, in __call__
    for v in app_iter:
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/error_printer.py", line 54, in __call__
    app_iter = self._application(environ, sub_app_start_response)
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/http_authenticator.py", line 195, in __call__
    return self._application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/dir_browser.py", line 169, in __call__
    return self._listDirectory(davres, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/dir_browser.py", line 271, in _listDirectory
    childList = davres.getDescendants(depth="1", addSelf=False)
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/dav_provider.py", line 457, in getDescendants
    for child in self.getMemberList():
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/dav_provider.py", line 421, in getMemberList
    for name in self.getMemberNames():
  File "/usr/local/lib/python2.7/dist-packages/wsgidav/fs_dav_provider.py", line 218, in getMemberNames
    name = name.decode(sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)
```

**Comment by mar10** [comment]
In general unicode is already supported, so we need more information on you scenario:
what version are you using, how installed, what OS, what steps to reproduce, ...?

**Comment by sarnobat** [comment]
# Reproduction steps
- In a browser, navigate to a folder that contains a file with UTF-8 characters (Spanish in my case).
```
/Unsorted/videos/Atletico/1970s/intercontinental 1974 atlético   independiente.mp4
```
# Version
```
2.2.4
```
# Installation steps
```
sudo apt-get install wsgidav
```
# Platform
```
Linux nuc 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:50 UTC 2017 i686 i686 i686 GNU/Linux
```
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by mar10** [comment]
@sarnobat Could you check if this is fixed with v2.3.0?

**Comment by sarnobat** [comment]
Thanks for the reply. 

Notes to self

h2. Installation

```

python setup.py build
sudo python setup.py install
```

**Comment by sarnobat** [comment]
No, same issue:

```
UnicodeDecodeError('ascii', '@NuevoEstadioATM 11 de Mayo 2015. Obras Nuevo Estadio Atl\xc3\xa9tico de Madrid.mp4 .f137.part-Frag25', 57, 58, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 1152, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/server.py", line 974, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cheroot/wsgi.py", line 133, in respond
    for chunk in filter(None, response):
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/wsgidav_app.py", line 435, in __call__
    for v in app_iter:
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/debug_filter.py", line 161, in __call__
    for v in app_iter:
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/error_printer.py", line 54, in __call__
    app_iter = self._application(environ, sub_app_start_response)
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/http_authenticator.py", line 195, in __call__
    return self._application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/dir_browser.py", line 169, in __call__
    return self._listDirectory(davres, environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/dir_browser.py", line 271, in _listDirectory
    childList = davres.getDescendants(depth="1", addSelf=False)
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/dav_provider.py", line 457, in getDescendants
    for child in self.getMemberList():
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/dav_provider.py", line 421, in getMemberList
    for name in self.getMemberNames():
  File "/usr/local/lib/python2.7/dist-packages/WsgiDAV-2.3.0-py2.7.egg/wsgidav/fs_dav_provider.py", line 218, in getMemberNames
    name = name.decode(sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 57: ordinal not in range(128)
```

**Comment by n3storm** [comment]
hi @sarnobat , spanish language file here. You will find less problems if you setup wsgidav using a python3 environment.

**Comment by n3storm** [comment]
I can see at "dav_provider.py" error on line 394 `in getHref
    + self.getPreferredPath(), safe=safe)` that you are not using current wsgidav version.

Please install from this repo like this:
`pip install git+https://github.com/mar10/wsgidav.git`

check if you are using pip or pip3 command in your setup @sarnobat

**Comment by tsuku** [comment]
I probably meet a similar error. But now it is solved. I don't know if it can help you.
The error is that I cannot open the folder containing Unicode character name file through webdav.

Simply to say, the error I met is caused by *Linux locale setting* and *Windows encoding*.

---
## Environoment:
	Debian 8
	wsgidav 2.4.1 (installed by pip)
---
## locale

The original locale is
```
root@localhost:/# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
root@localhost:/#
```
Then, through apt-get install locales、dpkg-reconfigure locales、choose en_US.UTF-8、reboot.

Now, it is
````
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
````
Now, after *ls* command, file name of UTF can normally display on my PuTTY terminal. And wsgidav hasn't error.


## Windows encoding

I use WinSCP on Win10, upload some files to the Debian8, but after *ls* command, the file name in PuTTY terminal still displays ???. And wsgidav has error.

The reason is that my Win10 is not UTF encoding. And the UTF-8 encoding of WinSCP is default set to *Auto*.

Then, I set the UTF-8 encoding of WinSCP to *On*, upload once again, the file name is correctly displayed. And wsgidav hasn't error.

**Comment by n3storm** [comment]
Have you tried with python3 @tsuku? 
```
aptitude install python3-venv
python3 -m venv wsgidavenv
source wsgidavenv/bin/activate
pip install wsgidav
```
and then your wsgidav setup for your problematic files.

thanks

**Comment by tsuku** [comment]
Just now, I found an another error.

Simply to say, python2 wsgidav in systemd will come out error.
The error is that I cannot download or open the file and folder both containing Unicode character name (Chrome can't open or CarotDAV appears error).


The error I find is from that I want to set wsgidav in Systemd,

wsgidav.service is like that
```
ExecStart=/usr/local/bin/wsgidav -c /wsgidav.conf
```

Then run it through *systemctl restart wsgidav*. The error above-mentioned will come out.

But if I directly run wsgidav in terminal, it has no error.


My solution is using Python3.
After *apt-get install python3 python3-pip*、*pip3 install cheroot wsgidav*
wsgidav.service is modified by 
```
ExecStart=/usr/bin/python3 /usr/local/bin/wsgidav -c /wsgidav.conf
```
Then it has no error.

**Comment by tsuku** [comment]
@n3storm

In fact, it cost some time to deal with these errors.

In my comment about *locale* and *Windows encoding*, wsgidav has already run with *Systemd* and *python3*.

I just tried python3 as you said python3 wound have less problems.
But I hadn't realized python3 was necessary.


Today, in another Debian8 without python3, I try wsgidav with python2, it comes out the error above-mentioned. After comparing the setting, I find python3 is necessary.

---
python2,python3,python-pip,python3-pip all were installed by apt-get.
wsgidav was installed by pip or pip3

Version is that
```
Debian 8
pip 1.5.6 python 3.4.2
pip 1.5.6 python 2.7.9
wsgidav 2.4.1
```

**Comment by tsuku** [comment]
@n3storm

In fact, it cost some time to deal with these errors.

In my comment about *locale* and *Windows encoding*, wsgidav has already run with *Systemd* and *python3*.

I just tried python3 as you said python3 wound have less problems.
But I hadn't realized python3 was necessary.


Today, in another Debian8 without python3, I try wsgidav with python2, it comes out the error above-mentioned. After comparing their settings, I find python3 is necessary.

---
python2, python3, python-pip, python3-pip all were installed by apt-get.
wsgidav was installed by pip or pip3
Version is that
```
Debian 8
pip 1.5.6 python 3.4.2
pip 1.5.6 python 2.7.9
wsgidav 2.4.1
```

**Comment by tsuku** [comment]
@n3storm

In fact, it cost some time to deal with these errors.

In my comment about *locale* and *Windows encoding*, wsgidav has already run with *Systemd* and *python3*.

I just tried python3 as you said python3 wound have less problems.
But I hadn't realized python3 was necessary.


Today, in another Debian8 without python3, I try wsgidav with python2, it comes out the error above-mentioned. After comparing their settings, I find python3 is necessary.

---
python2,python3,python-pip,python3-pip all were installed by apt-get.
wsgidav was installed by pip or pip3

Version is that
```
Debian 8
pip 1.5.6 python 3.4.2
pip 1.5.6 python 2.7.9
wsgidav 2.4.1
```

**Comment by tsuku** [comment]
@n3storm

With en_US.UTF-8 locale and WinSCP UTF-8 on,
the files uploaded have no problem in wsgidav.

Only wsgidav run with python2 and Systemd, it has error.



Just now, with WinSCP UTF-8 off, I create a file named ×
Expectedly, I cannot open the folder containing that file.(wsgidav run by python3 and Systemd)

And errors are the same with yours.
```
...
20th line   filePath = filePath.encode("utf8")
21st line   UnicodeEncodeError: 'utf-8' codec can't encode character '\udca1' in position 19: surrogates not allowed
22nd line   ValueError("invalid literal for int() with base 10: ''",)
...
```

I guess that your file name probably isn't UTF-8 encoding.

**Comment by authmane512** [comment]
Hello, the error still occurs.

I tried to connect using Orgzly on Android.

I started WSGIDAV with python3 and my locales are in UTF-8, but the error still occurs:

```
# python3 /home/authmane/.local/bin/wsgidav --config ~/bin/wsgidav.yaml
10:59:55.921 - WARNING : App wsgidav.mw.cors.Cors(None).is_disabled() returned True: skipping.
10:59:55.934 - INFO    : WsgiDAV/4.0.1 Python/3.8.10 Linux-5.4.0-110-generic-x86_64-with-glibc2.29
10:59:55.935 - INFO    : Lock manager:      LockManager(LockStorageDict)
10:59:55.936 - INFO    : Property manager:  None
10:59:55.936 - INFO    : Domain controller: PAMDomainController('login')
10:59:55.937 - INFO    : Registered DAV providers by route:
10:59:55.938 - INFO    :   - '/:dir_browser': FilesystemProvider for path '/home/authmane/.local/lib/python3.8/site-packages/wsgidav/dir_browser/htdocs' (Read-Only)
10:59:55.938 - INFO    :   - '/': FilesystemProvider for path '/home/authmane/mynotes/orgzly' (Read-Write)
10:59:55.938 - WARNING : Basic authentication is enabled: It is highly recommended to enable SSL.
10:59:55.938 - WARNING : Could not import lxml: using xml instead (up to 10% slower). Consider `pip install lxml`(see https://pypi.python.org/pypi/lxml).
10:59:56.057 - INFO    : Running WsgiDAV/4.0.1 Cheroot/8.6.0 Python 3.8.10
10:59:56.057 - INFO    : Serving on http://0.0.0.0:8080 ...
11:03:34.996 - INFO    : 192.168.105.49 - (anonymous) - [2022-06-03 08:03:34] "PROPFIND /" depth=0, elap=0.001sec -> 401 Not Authorized
11:03:35.019 - ERROR   : Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 49, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 251, in __call__
    return self.handle_basic_auth_request(environ, start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 302, in handle_basic_auth_request
    auth_value = util.to_str(auth_value)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/util.py", line 87, in to_str
    s = str(s, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte

11:03:35.021 - ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 49, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 251, in __call__
    return self.handle_basic_auth_request(environ, start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 302, in handle_basic_auth_request
    auth_value = util.to_str(auth_value)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/util.py", line 87, in to_str
    s = str(s, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 83, in __call__
    raise as_DAVError(e)
wsgidav.dav_error.DAVError: 500

11:03:35.022 - ERROR   : e.src_exception:
'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte
11:03:35.023 - INFO    : 192.168.105.49 - (anonymous) - [2022-06-03 08:03:35] "PROPFIND /" depth=0, elap=0.010sec -> 500 Internal Server Error
11:03:35.927 - INFO    : 192.168.105.49 - (anonymous) - [2022-06-03 08:03:35] "PROPFIND /" depth=0, elap=0.000sec -> 401 Not Authorized
11:03:35.942 - ERROR   : Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 49, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 251, in __call__
    return self.handle_basic_auth_request(environ, start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 302, in handle_basic_auth_request
    auth_value = util.to_str(auth_value)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/util.py", line 87, in to_str
    s = str(s, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte

11:03:35.943 - ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 49, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 251, in __call__
    return self.handle_basic_auth_request(environ, start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 302, in handle_basic_auth_request
    auth_value = util.to_str(auth_value)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/util.py", line 87, in to_str
    s = str(s, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 83, in __call__
    raise as_DAVError(e)
wsgidav.dav_error.DAVError: 500

11:03:35.944 - ERROR   : e.src_exception:
'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte
11:03:35.951 - INFO    : 192.168.105.49 - (anonymous) - [2022-06-03 08:03:35] "PROPFIND /" depth=0, elap=0.007sec -> 500 Internal Server Error
11:03:36.480 - INFO    : 192.168.105.49 - (anonymous) - [2022-06-03 08:03:36] "PROPFIND /" depth=0, elap=0.000sec -> 401 Not Authorized
11:03:36.497 - ERROR   : Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 49, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 251, in __call__
    return self.handle_basic_auth_request(environ, start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 302, in handle_basic_auth_request
    auth_value = util.to_str(auth_value)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/util.py", line 87, in to_str
    s = str(s, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte

11:03:36.499 - ERROR   : Caught HTTPRequestException(HTTP_INTERNAL_ERROR)
Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 49, in __call__
    app_iter = self.next_app(environ, sub_app_start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 251, in __call__
    return self.handle_basic_auth_request(environ, start_response)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/http_authenticator.py", line 302, in handle_basic_auth_request
    auth_value = util.to_str(auth_value)
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/util.py", line 87, in to_str
    s = str(s, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/authmane/.local/lib/python3.8/site-packages/wsgidav/error_printer.py", line 83, in __call__
    raise as_DAVError(e)
wsgidav.dav_error.DAVError: 500

11:03:36.500 - ERROR   : e.src_exception:
'utf-8' codec can't decode byte 0xe0 in position 20: invalid continuation byte
11:03:36.502 - INFO    : 192.168.105.49 - (anonymous) - [2022-06-03 08:03:36] "PROPFIND /" depth=0, elap=0.005sec -> 500 Internal Server Error
```

My locales:
```
# locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_CH.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=de_CH.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=de_CH.UTF-8
LC_NAME=de_CH.UTF-8
LC_ADDRESS=de_CH.UTF-8
LC_TELEPHONE=de_CH.UTF-8
LC_MEASUREMENT=de_CH.UTF-8
LC_IDENTIFICATION=de_CH.UTF-8
LC_ALL=
```

**Comment by authmane512** [comment]
I solved the problem! It was because of a special character in my password using PAM authencation.

So basically, I just changed the password with one that contains only ASCII characters. :-)
